events {
    worker_connections 1024;
}

http {

    upstream meu_cluster {
        server web1:80;
        server web2:80;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://meu_cluster;
        }
    }
}